---
title: "Assignment 3"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r Load Packages, echo = FALSE, include = FALSE, message = FALSE, warning = FALSE}

library(tidyverse)
library(stargazer)
#load csv

hw3 <- read_csv("HW3Data.csv")


```

```{r Question 1, echo = FALSE}

# Create a linear probability model that predicts a respondent's probability of voting 'yes' on the ballot based on their age, income, NEP score, the risk reduction offered by the program (risk), and the cost of the program to that respondent (bid). 

lm_vote <- lm(formula = vote ~ risk + bid + NEP + income + age, data = hw3)

summary(lm_vote)



# Coefficients:
#       (Vote)               risk                bid                NEP     incomeone_percent         incomepoor  
#         0.1196977          0.0007445         -0.0010699          0.0158639          0.0088282          0.0027386  

#        incomerich    incomevery_rich         agetofifty         agetoforty         agetosixty        agetothirty  
#         0.0074891          0.0467922          0.0099816         -0.0201190         -0.0162261          0.0204401 




# Analyzing coefficients:


# For every additional unit of risk reduction, there is an increase in voting YES by 0.0007445.
# For every $1 increase in cost per household, there is a decrease in voting YES by 0.0010699.
# For every additional unit increase for NEP score, there is an increase in voting YES by 0.0158639.
# For every additional $1 increase in income for the top one percent of society, there is an increase in voting YES by 0.0088282.
# For every additional $1 increase in income for the poor communities of society, there is an increase in voting YES by 0.0027386.
# For every additional $1 increase in income for the rich communities of society, there is an increase in voting YES by 0.0074891.
# For every additional $1 increase in income for the very rich communities of society, there is an increase in voting YES by 0.0467922.
# For every additional person aged 41-50, there is an increase in voting YES by 0.0099816.
# For every additional person aged 31-40, there is an decrease in voting YES by 0.0201190.
# For every additional person aged 51-60, there is an decrease in voting YES by 0.0162261.
# For every additional person aged 18-30, there is an increase in voting YES by 0.0204401.


# Put linear model into stargazer table 

stargazer(lm_vote)



```

```{r Question 2, echo = FALSE}

## Based on this regression, what can you say about the value of a single prevented whale death? (Hint: Think about how risk reduction for all whales translates into the number of whale deaths avoided)



```

